#!/bin/bash
# Creates separate mirrors for each component in a distribution.
# Useful until aptly implements mirror-as-is.

set -e

NAME="$1"
URL="$2"
DIST="$3"
ARCH="$4"

if [ -z "$DIST" ]; then
	echo "Usage: $0 <name> <archive url> <distribution> [<architecture,architecture>]"
	exit 1
fi

if [[ -n "$ARCH" ]]; then
   ARCHITECTURE="-architectures=$ARCH"
fi

COMPONENTS=$(curl -s "$URL/dists/$DIST/Release" | grep "^Components: " | cut -d' ' -f2-)

for COMPONENT in $COMPONENTS; do
	echo aptly $ARCHITECTURE mirror create "$NAME#$COMPONENT" "$URL" "$DIST" "$COMPONENT"
	aptly $ARCHITECTURE mirror create "$NAME#$COMPONENT" "$URL" "$DIST" "$COMPONENT"
done
